import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const pieceNames={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'};
export function render(C,root){
 const css=fs.readFileSync(path.join(root,'source/style.css'),'utf8'),pieceDir=path.join(root,'source/pieces'),pieces={};for(const c of ['w','b'])for(const p of ['K','Q','R','B','N','P'])pieces[c+p]=fs.readFileSync(path.join(pieceDir,c+p+'.svg'),'utf8');
 const license=fs.readFileSync(path.join(pieceDir,'COPYING.txt'),'utf8').replaceAll('--','—'),website=`https://knightway8.github.io/${C.repo}/`,repo=`https://github.com/knightway8/${C.repo}`;
 const write=(name,s)=>{const full=path.join(root,name);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,s);};
 function board(fen,marked=[]){let squares='',rank=8;for(const row of fen.split(' ')[0].split('/')){let file=0;for(const char of row){const n=/\d/.test(char)?Number(char):1;for(let j=0;j<n;j++){const square='abcdefgh'[file]+rank,empty=/\d/.test(char),white=char===char.toUpperCase();squares+=`<div class="sq${(file+rank)%2?' dark':''}${marked.includes(square)?' marked':''}" role="img" aria-label="${square}: ${empty?'empty':(white?'White ':'Black ')+pieceNames[char.toLowerCase()]}">${empty?'':`<span class="piece" aria-hidden="true">${pieces[(white?'w':'b')+char.toUpperCase()]}</span>`}</div>`;file++;}}rank--;}
 return `<div class="board-frame"><div class="ranks" aria-hidden="true">${[8,7,6,5,4,3,2,1].map(r=>`<span>${r}</span>`).join('')}</div><div class="board" role="group" aria-label="Chess diagram with White at the bottom">${squares}</div><div class="files" aria-hidden="true">${[...'abcdefgh'].map(f=>`<span>${f}</span>`).join('')}</div></div>`;}
 function diagram(fen,label,caption,marks=[]){return `<figure class="diagram"><div class="label">${esc(label)}</div>${board(fen,marks)}<figcaption>${esc(caption)}</figcaption></figure>`;}
 const turn=fen=>fen.split(' ')[1]==='w'?'White':'Black';
 const top=prefix=>`<a class="skip" href="#main">Skip to lesson</a><header class="top"><div class="wrap"><a class="brand" href="${prefix}index.html">Chess / Explained</a><a href="${prefix}index.html">${esc(C.title)} · Lesson directory</a></div></header>`;
 const credits=(prefix,lesson)=>`<footer class="foot"><p>Original AI-created teaching material. Diagrams use Cburnett pieces by Colin M. L. Burnett, GPL version 2 or later. ${lesson?'This lesson includes its own diagrams and styles; it can be saved and read on its own.':''}</p><div class="links"><a href="${prefix}sources.html">Sources & artwork credits</a><a href="${repo}">Repository & README</a>${lesson?`<a href="${lesson.filename}" download>Save this lesson as HTML</a>`:`<a href="${repo}/archive/refs/heads/main.zip">Download the collection</a>`}</div></footer>`;
 function page(title,body,prefix='',name='index.html',lesson=null){return `<!doctype html><html lang="en" style="--accent:${C.color}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(lesson?lesson.lead:C.subtitle)}"><link rel="canonical" href="${website}${name}"><title>${esc(title)} · Chess / Explained</title><style>${css}</style></head><body>${top(prefix)}<main id="main" class="wrap">${body}${credits(prefix,lesson)}</main></body></html>\n<!-- Cburnett chess-piece artwork © Colin M. L. Burnett. GPL-2.0-or-later. The SVG artwork is included in source form above; unmodified originals and provenance are in source/pieces/. License text follows for people keeping this standalone file.\n${license}\n-->\n`;}
 function lessonBody(l,book=false){const final=l.steps.at(-1),previous=C.lessons[l.number-2],next=C.lessons[l.number];const finalCaption=l.checkmate?`${turn(l.finalFen)} is checkmated.`:l.stalemate?'Stalemate: the game is drawn.':`${turn(l.finalFen)} to move after the illustrated line. The gold border marks the last destination.`;
 return `<article class="lesson"${book?` id="lesson-${l.number}"`:''}><header class="intro"><p class="eyebrow">${C.repo} · ${esc(C.title)} · LESSON ${String(l.number).padStart(2,'0')} / 16</p><h1>${esc(l.title)}</h1><p class="lead">${esc(l.lead)}</p></header><section class="prose"><h2>Read the position</h2><p>${esc(l.read)}</p>${l.opening?.length?`<p class="opening"><strong>Moves leading to the first diagram:</strong> ${esc(l.openingPgn.replace(/\s*\*\s*$/,''))}</p>`:''}</section><div class="diagrams">${diagram(l.fen,'Before the line',`${turn(l.fen)} to move. White is shown at the bottom.`)}${diagram(l.finalFen,`After ${final.moveNumber}${final.side==='w'?'.':'…'} ${final.san}`,finalCaption,[final.uci.slice(2,4)])}</div><section class="prose"><h2>The moves, explained</h2><ol class="moves">${l.steps.map(s=>`<li><span class="move">${s.moveNumber}${s.side==='w'?'.':'…'} ${esc(s.san)}</span><span>${esc(s.note)}</span></li>`).join('')}</ol><h2>Why it works</h2><p>${esc(l.explain)}</p><h2>Where care is needed</h2><p>${esc(l.caution)}</p><aside class="remember"><strong>The point to keep</strong><p>${esc(l.remember)}</p></aside></section>${book?'':`<nav class="navigation" aria-label="Lesson navigation">${previous?`<a href="${previous.filename}">← Lesson ${String(previous.number).padStart(2,'0')}</a>`:'<a href="../index.html">← Lesson directory</a>'}<a href="../index.html">All 16 lessons</a>${next?`<a href="${next.filename}">Lesson ${String(next.number).padStart(2,'0')} →</a>`:'<a href="../sources.html">Sources →</a>'}</nav>`}</article>`;}
 for(const l of C.lessons)write('lessons/'+l.filename,page(l.title,lessonBody(l),'../','lessons/'+l.filename,l));
 const collection=`<div class="series">${C.series.map(s=>`<a href="https://knightway8.github.io/${s.repo}/"><small>${s.repo}</small><strong>${esc(s.title)}</strong><small>16 standalone lessons</small></a>`).join('')}</div>`;
 write('index.html',page(C.title,`<section class="home-intro"><div><p class="eyebrow">A SMALL LIBRARY OF DIRECT LESSONS</p><h1>${esc(C.title)}.</h1><p class="lead">${esc(C.subtitle)}</p><p>${esc(C.audience)}</p><p>Choose a title below. Each lesson explains one idea, shows its moves, and leaves the complete explanation on the page.</p><a href="lessons/${C.lessons[0].filename}">Read lesson 01 →</a></div>${diagram(C.lessons[0].fen,'An example from the first lesson',`${turn(C.lessons[0].fen)} to move. Clear diagrams accompany every lesson.`)}</section><div class="facts"><div><strong>16</strong>complete lessons</div><div><strong>32</strong>board diagrams</div><div><strong>Read anywhere</strong>each lesson is one HTML file</div></div><section><h2>The lesson directory</h2><ol class="lesson-index">${C.lessons.map(l=>`<li><a href="lessons/${l.filename}"><span class="number">${String(l.number).padStart(2,'0')}</span><span><strong>${esc(l.title)}</strong><small>${esc(l.lead)}</small></span></a></li>`).join('')}</ol></section><section><h2>Read or print the whole collection</h2><p><a href="collection.html">Open all 16 lessons on one printable page</a>, or <a href="downloads/lesson-notes.md">download the text notes</a>. Use your browser’s Print command to print or save as PDF.</p></section><section><h2>The four companion collections</h2>${collection}</section>`));
 write('collection.html',page(C.title+' — complete collection',`<div class="book"><header class="book-title"><p class="eyebrow">CHESS / EXPLAINED · ${C.repo}</p><h1>${esc(C.title)}</h1><p class="lead">${esc(C.subtitle)}</p><p>Sixteen direct lessons. Use the browser’s Print command to print this collection or save it as PDF. Each lesson starts on a fresh page in print.</p></header>${C.lessons.map(l=>lessonBody(l,true)).join('')}</div>`,'','collection.html'));
 const tablebase=C.repo==='chess18'?'<p>Every initial endgame position and every move in its illustrated continuation was checked with the Lichess Syzygy service. Each line preserves its starting win or draw. The saved results are included with the lesson data. These exact results concern the displayed small positions, not every similar-looking position.</p>':'';
 write('sources.html',page('Sources and verification',`<section class="intro"><p class="eyebrow">REFERENCES, SCOPE & CREDITS</p><h1>How these lessons were checked.</h1><p class="lead">The teaching text is original, and the diagrams give concrete positions that can be inspected independently.</p></section><section class="prose"><h2>Moves and diagrams</h2><p>All starting positions, opening sequences, and illustrated moves were checked for legal board state with chess.js. Checkmates and stalemates were checked explicitly. Most tactical lines illustrate a mechanism through one legal continuation; they are not claims that every opponent reply is forced or that every displayed move is an engine’s only choice.</p>${tablebase}<p><a href="VERIFICATION.json">Read the validation record</a> · <a href="source/course.json">Read the position and lesson data</a> · <a href="downloads/illustrated-lines.pgn">Download the illustrated lines as PGN</a>.</p><h2>Primary references</h2><ul class="source-list"><li><a href="https://handbook.fide.com/chapter/e012023">FIDE Laws of Chess</a> — legal moves, castling, promotion, checkmate, and stalemate.</li><li><a href="https://github.com/jhlywa/chess.js">chess.js</a> — the move-validation library used during preparation, with its <a href="vendor/chess-LICENSE.txt">BSD-2-Clause notice</a>.</li><li><a href="https://github.com/lichess-org/lila-tablebase">Lichess tablebase server</a> — documentation for exact small-piece endgame results.</li><li><a href="source/pieces/README.md">Cburnett artwork credits and source provenance</a> — Colin M. L. Burnett’s vector pieces, supplied in source form under <a href="source/pieces/COPYING.txt">GPL version 2 or later</a>.</li></ul><h2>Using these pages</h2><p>Every lesson contains its own styles and piece artwork. It can be saved and read as a single HTML file without an account or internet connection. The reading pages have no JavaScript, answer forms, progress trackers, or hidden answer sections.</p><h2>Corrections</h2><p>Report a specific lesson or move in <a href="${repo}/issues">the repository’s issues</a>. For maintenance, edit source/course.json, rebuild the pages with node tools/build.mjs, and run node tools/verify.cjs. Keep the original board position and the explanation consistent.</p></section>`,'','sources.html'));
 write('404.html',page('Find a lesson',`<section class="intro"><p class="eyebrow">LESSON DIRECTORY</p><h1>Find your lesson.</h1><p><a href="${website}">Open the complete lesson directory</a>.</p></section>`,'','404.html'));
 write('downloads/lesson-notes.md',`# ${C.title}\n\n${C.subtitle}\n\n${C.lessons.map(l=>`## ${l.number}. ${l.title}\n\n${l.lead}\n\n${l.read}\n\n${l.steps.map(s=>`- **${s.moveNumber}${s.side==='w'?'.':'...'} ${s.san}** — ${s.note}`).join('\n')}\n\n${l.explain}\n\n${l.caution}\n\n**Remember:** ${l.remember}\n`).join('\n')}`);
 write('downloads/illustrated-lines.pgn',C.lessons.map(l=>`[Event "${C.title}: lesson ${l.number}"]\n[Site "${website}lessons/${l.filename}"]\n[Date "2026.09.05"]\n[Round "-"]\n[White "Illustration"]\n[Black "Illustration"]\n[Result "${l.checkmate?(l.finalFen.split(' ')[1]==='b'?'1-0':'0-1'):l.stalemate?'1/2-1/2':'*'}"]\n[SetUp "1"]\n[FEN "${l.fen}"]\n\n${l.steps.map(s=>`${s.moveNumber}${s.side==='w'?'.':'...'} ${s.san} { ${s.note.replaceAll(/[{}]/g,'')} }`).join(' ')} ${l.checkmate?(l.finalFen.split(' ')[1]==='b'?'1-0':'0-1'):l.stalemate?'1/2-1/2':'*'}\n`).join('\n'));
 write('README.md',`# ${C.title}\n\n**[Read the GitHub Pages collection](${website})**\n\n${C.subtitle}\n\n${C.audience}\n\n## Format\n\n- 16 direct lessons, each a self-contained HTML file with its own styles and embedded vector chess pieces.\n- 32 lesson diagrams: the starting position and the result of the fully explained line.\n- Visible explanations throughout: no answer inputs, hidden solutions, scores, progress controls, or client-side JavaScript.\n- One printable collection, Markdown notes, and PGN move sequences.\n\nA single lesson can be saved or copied on its own and read offline. Navigation to other lessons requires those neighboring files, but the lesson text and diagrams do not. Open [collection.html](collection.html) and use your browser’s Print command to print or save as PDF.\n\n## Lessons\n\n${C.lessons.map(l=>`${l.number}. [${l.title}](lessons/${l.filename})`).join('\n')}\n\n## Four companion collections\n\n| Repository | Collection | Live site |\n| --- | --- | --- |\n${C.series.map(s=>`| [${s.repo}](https://github.com/knightway8/${s.repo}) | ${s.title} | [Read](https://knightway8.github.io/${s.repo}/) |`).join('\n')}\n\n## Verification and maintenance\n\n[Sources and verification](sources.html) explains the scope. [VERIFICATION.json](VERIFICATION.json) records legal move, diagram, PGN, self-containment, and directory-size checks. The endgame collection also includes exact tablebase results. Illustrative tactical continuations are not claims of exhaustive analysis.\n\nEdit [source/course.json](source/course.json), run \`node tools/build.mjs\`, then run \`node tools/verify.cjs\`. All directories must remain below 1,000 entries.\n\nGitHub Pages publishes the root of \`main\` through \`.nojekyll\`. Default-branch rules require pull requests and block force pushes and branch deletion, without bypass actors. An owner can still alter settings or delete a repository.\n\n## Credits\n\nOriginal AI-created lessons prepared for knightway8. Cburnett pieces by Colin M. L. Burnett are supplied under GPL-2.0-or-later, with [unmodified SVG sources, provenance, and license](source/pieces/README.md). The artwork’s full license is also embedded as a comment in each standalone HTML file. chess.js is used for authoring checks under its [BSD-2-Clause license](vendor/chess-LICENSE.txt).\n`);
 write('.nojekyll','');write('.gitattributes','* text=auto eol=lf\n');write('.gitignore','.DS_Store\nThumbs.db\n');write('CONTRIBUTING.md','# Corrections and improvements\n\nDescribe the exact lesson, board, or move that needs correction. Update source/course.json, regenerate with node tools/build.mjs, and validate with node tools/verify.cjs. Preserve the direct reading format: no question forms or hidden answers. Use a branch and pull request, keep protections active, and verify the published lesson after merging.\n');
 write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['index.html','collection.html','sources.html',...C.lessons.map(l=>'lessons/'+l.filename)].map(f=>`<url><loc>${website}${f}</loc></url>`).join('')}</urlset>`);write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${website}sitemap.xml\n`);
}
const here=fileURLToPath(import.meta.url);if(process.argv[1]&&path.resolve(process.argv[1])===here){const root=path.resolve(path.dirname(here),'..');render(JSON.parse(fs.readFileSync(path.join(root,'source/course.json'),'utf8')),root);console.log('Rebuilt direct lessons.');}
